spin_manifest_version = 2

[application]
name = "rekuest componenet example"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-example"

[component.spin-example]
source = "service.wasm"
allowed_outbound_hosts = ["http://*", "https://*"]
[component.spin-example.build]
command = "./build.sh"
watch = ["src/**/*.rs", "Cargo.toml"]
